name: Deploy

concurrency: deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Sync production
        run: |
          ./node_modules/@markwylde/ftp-deploy/index.js .github/workflows/deployConfig.js
        env:
          FTP_HOSTNAME: ${{ secrets.ftp_server }}
          FTP_USERNAME: ${{ vars.ftp_username }}
          FTP_PASSWORD: ${{ vars.ftp_password }}
